### ISSUE TITLE
backup.php files not downloadable

### ISSUE THREAD

**Issue by stemind** [u5cms/u5cms#27] opened 2021-12-28 09:25 UTC
in u5admin/backend.php (directly surfable) the 3 files are genarated where as the first and the second one are correctly e-mailed in addition, the files are not downloadable.

They are correctly streamed through ff.php  (first and second) and fff.php (third).

ff.php and fff.php shall reuse the current login and not trigger a login.

**Comment by mrolli** [comment] 2021-12-28 11:21
At http://u5cms.nemulbnesraam.ch/u5admin/backup.php this works for me in Chrome as well as in Safari without any re-login.

Will test again in another context, but meanwhile bundle a new release for the other fixed issues.

**Comment by stemind** [comment] 2021-12-29 09:11
In a from-scratch-install of 10.1.0 they are downloadable again without any problems.

**Comment by mrolli** [comment] 2021-12-29 11:04
Closing as not reproducible anymore. Feel free to reopen this issue in case it occurs again.

**Closed by mrolli** 2021-12-29 11:04 UTC
Labels: bug, invalid
